name = "pachadb-consolidator"
main = "build/worker/shim.mjs"
compatibility_date = "2023-07-24"

usage_model = "bundled"

kv_namespaces = [
  { binding = "pachadb-entities-store", id = "f65a15f705814e5eb00202ef19ed27ca" },
  { binding = "pachadb-facts-store", id = "88c04e76bdb04ff78783cc5d850c86ac" },
]

[[queues.consumers]]
queue = "pachadb-facts-consolidation"
max_batch_size = 1
max_batch_timeout = 0

[[queues.producers]]
queue = "pachadb-entities"
binding = "pachadb-entities-queue"

[build]
command = "cargo install worker-build && worker-build --release"
